[project]
name = "summarize-it"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "certifi==2025.11.12",
    "charset-normalizer==3.4.4",
    "colorama==0.4.6",
    "datasets>=4.4.1",
    "filelock==3.20.0",
    "fsspec==2025.10.0",
    "huggingface-hub==0.36.0",
    "idna==3.11",
    "joblib==1.5.2",
    "numpy==2.3.5",
    "packaging==25.0",
    "pandas==2.3.3",
    "python-dateutil==2.9.0.post0",
    "pytz==2025.2",
    "pyyaml==6.0.3",
    "regex==2025.11.3",
    "requests==2.32.5",
    "safetensors==0.7.0",
    "scikit-learn==1.7.2",
    "scipy==1.16.3",
    "six==1.17.0",
    "threadpoolctl==3.6.0",
    "tokenizers==0.22.1",
    "tqdm==4.67.1",
    "transformers==4.57.3",
    "typing-extensions==4.15.0",
    "tzdata==2025.2",
    "urllib3==2.5.0",
]
